using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace DoorScript
{
	[RequireComponent(typeof(AudioSource))]


public class Door : MonoBehaviour {
	public bool open;
	public float smooth = 1.0f;
	float DoorOpenAngle = -90.0f;
    float DoorCloseAngle = 0.0f;
	public AudioSource asource;
	public AudioClip openDoor,closeDoor;
    public Transform teleportPoint; // Punto di teletrasporto (inizio stanza)
                                        // Use this for initialization
        void Start () {
		asource = GetComponent<AudioSource> ();
	}
	
	// Update is called once per frame
	void Update () {
		if (open)
		{
            var target = Quaternion.Euler (0, DoorOpenAngle, 0);
            transform.localRotation = Quaternion.Slerp(transform.localRotation, target, Time.deltaTime * 5 * smooth);
	
		}
		else
		{
            var target1= Quaternion.Euler (0, DoorCloseAngle, 0);
            transform.localRotation = Quaternion.Slerp(transform.localRotation, target1, Time.deltaTime * 5 * smooth);
	
		}  
	}

	public void OpenDoor(){
		open =!open;
		asource.clip = open?openDoor:closeDoor;
		asource.Play ();
	}

	private void OnTriggerEnter(Collider other)
	{
		if (other.CompareTag("Player")) // Assicurati che il player abbia il tag "Player"
		{
			CharacterController cc = other.GetComponent<CharacterController>();
			if (cc != null)
			{
				cc.enabled = false; // Disabilita CharacterController per evitare problemi di collisione
				other.transform.position = teleportPoint.position;
				other.transform.rotation = teleportPoint.rotation;
				cc.enabled = true; // Riabilita il CharacterController
			}
		}
	}
}
}